---
project_name: flasktutorial
project_home: /home/flasktutorial
project_root: /home/flasktutorial/project
virtualenv_directory: /home/flasktutorial/.venv
project_repo: git@github.com:rafaelhenrique/flask_tutorial.git
private_key_github: /home/<your local user here>/.ssh/id_rsa
public_key_github: /home/<your local user here>/.ssh/id_rsa.pub
management_user: <your remote user here>
secret_key: '<your secret key here>'
server_name: '<your server name here>'
database_uri: 'sqlite:///tvseries.sqlite3'
production_variables:
    SECRET_KEY: "{{ secret_key }}"
    SERVER_NAME: "{{ server_name }}"
    DATABASE_URI: "{{ database_uri }}"
system_packages:
  - build-essential
  - python3
  - python3-dev
  - python3-venv
  - nginx
  - supervisor
